### ISSUE TITLE
Add command to transfer hotspot

### ISSUE THREAD

**Issue by BoxedBrain** [helium/helium-ledger-cli#24]
As of today, there is no possibility to manage a hotspot, which was transferred to a Ledger wallet.
Therefore, a command to transfer the hotspot to a different wallet is needed - otherwise the hotspot become unusable.

**Comment by juwei80** [comment]
Vote +1

**Comment by mandros1985** [comment]
Vote + 1 !!!

Also, the possibility to sync the ledger generated wallet with bobber app would be nice 

Unfortunately, this is not possible yet

**Comment by k-thornton** [comment]
If someone manages to transfer their hotspot ownership over to their Ledger account, they end up in a pretty sticky situation if they can't use the CLI to transfer ownership back to a Helium Wallet account.  I also vote +1 (heck give it +2) on this feature :)

**Comment by WannesLimbourg** [comment]
now that the blue app doesn't work anymore. and i added my miner to my ledger adress i can't transfer it back to get al usability. how do i solve this issue.

**Comment by mandros1985** [comment]
are there any plans for this ? :)

**Comment by AK1928** [comment]
I still have this problem! Please fix! Thank you!

**Comment by mandros1985** [comment]
@lthiery can You suggest an alternative of some sort? Please just don't tag and ignore it. There are at least a few people having this issue

**Comment by lthiery** [comment]
@mandros1985 The current helium-ledger-cli and helium-ledger-app are going to be legacy soon.

There will be new tooling based on Solana and I've been told that hotspot transfers will be supported! I'm not actively involved with it, but @ChewingGlass might be able to share more details.

**Comment by mandros1985** [comment]
Fantastic news, please share some more details if possible here, so that anyone in need can be informed :) Thanks !

**Comment by juwei80** [comment]
Any news on this, @lthiery, @ChewingGlass?

**Comment by BoxedBrain** [comment]
@mandros1985 looks like you solved it? Could you write up a short guide how you did it? That would be amazing and appreciated by all of us! 🚀

**Comment by mandros1985** [comment]
will write a full user story tomorrow :)

**Comment by mandros1985** [comment]
ok so I was lucky enough to migrate with success to solana from the black wallet app 

Let me just underline before I explain further that I did the blue app migration to black app wallet 

Being on the black helium app, I attached 5 of my miners (bobcat) to my ledger wallet that was connected then to the black app 

Doing that time, I have disabled permanently for me the function to transfer the devices from the black app anywhere and my devices were stuck on my ledger helium wallet connected to the black app 

After a year or so, helium meanwhile voted to move to solana blockchain. 

And on some of the GitHub issue threads, it was said that this will unlock potentially the option of transferring the miners. 

During all that time, the miners worked and mined rewards directly to my ledger wallet - so all in all, it was not bad - except for the transfer function, it was fine. 

When the helium moved to solana, the first thing I did is I moved the wallets inside the black app. Correct me if I am wrong, but I do think that there was some sort of migration inside the black app itself. 

The connected ledger wallet inside the black app was unable to claim rewards (IOT) tokens. Or do much anyways. 
The first thing I did is I tried the migration tool https://docs.helium.com/solana/migration/ledger/  

On my ledger nano X I had to install solana app and helium-solana app 

At first, it did not work, but the devs fixed it. Anyway, after the fix 

I have moved through the migration tool with no problems - look up the YT video to be sure You do what is there 1 to 1 

When migrated, You can now connect the wallet to a solana type wallet - I used solflare 

Simply connect Your ledger device via solana app inside ledger to solflare and import account 0 

Now You will see all the IOT / Sol / HELIUM assets 

In the nft section, if You have devices connected to the ledger You will see them, and now You will be able to transfer them to a different solana wallet 

Make sure You top up a bit of solana token to the now migrated to solflare wallet to be able to do the transfers

Also, since now, the wallet is in the black app and the solana wallet. You have to remember that inside solflare You cannot claim IOT tokens, but You can in the black app o_0 it's confusing as for now, but there it is ... 

Anyway that was my story - I'm just happy I regained controll over my devices ;)

**Comment by BoxedBrain** [comment]
Thanks @mandros1985!
