### ISSUE TITLE
Allow alternative derivation paths for advanced recovery options.

### ISSUE THREAD

**Issue by k-thornton** [helium/helium-ledger-cli#28]
It appears that Opolo and Ledger wallets differ in how they derive Helium accounts, so when you recover an Opolo-generated seed phrase into a Ledger, you don't get the same Helium accounts back out when you use the helium-ledger-cli.  Would love if it was possible to support alternative derivation paths so these users can locate and recover their accounts.

**Comment by Modatech16** [comment]
I am having the same issue with the Opolo wallet. I also have 3 others that I know of that have contacted me with the issue and they cannot get their HNT from Opolo over to the new Helium wallet via Ledger CLI or any other method.

We can get the first account over via CLI, account 0, but other HNT addresses under the same wallet are not able to import most likely due to a different derviation. After account O the rest of the addresses imported/ created are completely new addresses, not the ones that were created on the Opolo.

Thank you, I appreciate your time.

**Comment by kellybyrd** [comment]
Just heard from a Discord user that he got the derivation path Opolo uses. It is `m/44'/904'/0'/0'/n'`
This looks like Opolo is using the last slot (called `index` in the BIP44 spec) for different accounts while the Ledger HNT app is correctly using the third slot (right after coin type =`904` ) as the account. Is it possible to change the Ledger app to scan all indexes for a given account? so for account 3 it would do `m/44'/904'/3'/0'/0'` then  `m/44'/904'/3'/0'/1'`, etc.

Also, shouldn't this issue be on the https://github.com/helium/helium-ledger-app github?

**Comment by lthiery** [comment]
I hadn't gotten notifications about this issue, apologies. I'm afraid we don't have time to develop this feature in particular, as the Solana migration is coming quite soon and the next Ledger release is slotted to support that.

However, you should be able to use any standard hardware wallet recovery tool to derive the specific private key using your seed words and the bip44 derivation path of interest, as it seems you've figured out how Opolo does it.

Alternately, you could try compiling your own version of [the Helium Ledger App](https://github.com/helium/helium-ledger-app) and side-loading it. If you change [this line of code](https://github.com/helium/helium-ledger-app/blob/master/src/txns/helium.c#L73
) to be: 
```c
    uint32_t bip32Path[] = {44 | 0x80000000, INDEX | 0x80000000, 0x80000000, 0x80000000, account | 0x80000000};
```

At that point, I think you will have a special version of the Helium Ledger App that simply complies with the same Opolo definition.

**Comment by kellybyrd** [comment]
Thanks for the reply, I worried  it was likely too late.

> However, you should be able to use any standard hardware wallet recovery tool to derive the specific private key using your seed words

Assuming I (not really me, but for example) could do this, how could I then  move assets to the "index 0" account with this information? I would need something that new how to send Payment_V2 to the existing Helium blockchain, right?

**Comment by lthiery** [comment]
Yes, you'd basically have to assemble the transaction, serialize it as a protobuf, sign the protobuf and at the signature to the transaction, then serialize and send the transaction. The [regular CLI wallet](https://github.com/helium/helium-wallet-rs/blob/master/src/cmd/pay.rs) is probably a good template for that. Also note that things will be different after the Solana change and you'll need to do similar with Solana transactions.

**Comment by k-thornton** [comment]
It would likely be easier (and safer!) to just use Opolo to send everything to account 0 and then you’d be good to go.

I say “safer” because the recovery option above involves entering your seed phrase into a computer which for Ledger users should always be avoided.

**Comment by lthiery** [comment]
> It would likely be easier (and safer!) to just use Opolo to send everything to account 0 and then you’d be good to go.

Oh, yes, I definitely agree.

**Comment by kellybyrd** [comment]
> It would likely be easier (and safer!) to just use Opolo to send everything to account 0 and then you’d be good to go.

It would. but Opolo appears to have abandoned the Helium project. Their software does not support payment_v2 and payment_v1 is no longer supported on the chain.  So no way to move things.

**Comment by Modatech16** [comment]
> > It would likely be easier (and safer!) to just use Opolo to send everything to account 0 and then you’d be good to go.
> 
> It would. but Opolo appears to have abandoned the Helium project. Their software does not support payment_v2 and payment_v1 is no longer supported on the chain. So no way to move things.

I'm in the same exact boat and so are 4 others that I know of that have been reaching out to me for a solution.

**Comment by Modatech16** [comment]
Has there been any solution implemented to address this issue?
thank you.

**Comment by Modatech16** [comment]
I see that this was just set to 'complete.' Was there a solution? I am still unable to access my coins.

**Comment by lthiery** [comment]
The issue is marked as "wont-fix" long ago because this problem lies with Opolo (1) abandoning support and (2) using a non-standard Helium derivation path. This repository exists for the Helium Ledger App which is now deprecated since the Solana migration.

I can make the two following suggestions, but beyond that, you should take this up with Opolo:

* find some software that will let you specify the derivation path of your Solana wallet. You can create the wallet using the Opolo derivation path for HNT (instead of the standard Solana one) and your coins will be at that address. The downside is, you've made a hot wallet out of your hardware seed and you might worry about anything else using that seed.
* you could compile a custom version of the Helium-Solana transition app that uses the Opolo derivation path. The Helium-Solana transition app was a very simple fork of the Solana app and this [one commit](https://github.com/helium/helium-ledger-app/commit/226bdaa2c0a441bf3a2b1141fcb22c325ebd16de) is all that was done. What's nice is it is setup to migrate coins from a non-Solana derivation path to the standard Solana derivation path; that's exactly what you want to do. If you compile it with the Opolo path and load it, you can follow [the standard migration instructions](https://docs.helium.com/solana/migration/ledger/). After that, you use the standard Solana wallet.

**Comment by Modatech16** [comment]
Thank you, I have tried contacting Opolo for the past 18 months and the CEO just ignores me and states that it was Helium's problem. I'm aware that is not the case but he just rugged me and a few other fellow US Marine veterans that are in the same boat due to my recommendation. 

Do you have any suggestions on software that I can use?

I really appreciate your reply as well as your time. I've felt like a complete fool for quite some time now.

Thank again.

**Comment by lthiery** [comment]
I'm sorry Opolo isn't providing support. If they support Solana, perhaps they would just implement the same migration method we did with Ledger? It seems you personally know a few people stranded this way but there may be quite a few more that they could "get off their back" by helping with the migration to the standard Solana wallet.

If you want to proceed with the software-based path... I haven't come across a GUI-based Solana wallet that lets you specify the derivation path. If I had to do this, I would break this into a two steps:

1) derive the specific private key that Opolo created from the derivation path + seed. If you can play around with Python, something like [this](https://github.com/ismailakkila/bip32) should do the trick.
2) import this private key into the [Solana CLI](https://docs.solana.com/cli) and do your transactions. The CLI just wants a file with the bytes written in an array: `[1,2,3...]`

**Comment by Modatech16** [comment]
Thank you very much; greatly appreciated.

**Comment by lthiery** [comment]
@Modatech16 actually for step 1, you might try this: https://docs.solana.com/wallet-guide/paper-wallet#hierarchical-derivation

It looks like it allows you to specify derivation path

**Comment by Modatech16** [comment]
> The issue is marked as "wont-fix" long ago because this problem lies with Opolo (1) abandoning support and (2) using a non-standard Helium derivation path. This repository exists for the Helium Ledger App which is now deprecated since the Solana migration.
> 
> I can make the two following suggestions, but beyond that, you should take this up with Opolo:
> 
> * find some software that will let you specify the derivation path of your Solana wallet. You can create the wallet using the Opolo derivation path for HNT (instead of the standard Solana one) and your coins will be at that address. The downside is, you've made a hot wallet out of your hardware seed and you might worry about anything else using that seed.
> * you could compile a custom version of the Helium-Solana transition app that uses the Opolo derivation path. The Helium-Solana transition app was a very simple fork of the Solana app and this [one commit](https://github.com/helium/helium-ledger-app/commit/226bdaa2c0a441bf3a2b1141fcb22c325ebd16de) is all that was done. What's nice is it is setup to migrate coins from a non-Solana derivation path to the standard Solana derivation path; that's exactly what you want to do. If you compile it with the Opolo path and load it, you can follow [the standard migration instructions](https://docs.helium.com/solana/migration/ledger/). After that, you use the standard Solana wallet.

Just another quick question, once I compile the new app, how would I get into the Ledger or Ledger Live?

**Comment by lthiery** [comment]
What ledger are you using? It's only possible to load the app onto Nano S. The "make load" command documented here explains it: https://github.com/helium/helium-ledger-app#development

I see the link to the ledger docs there is broken, but you basically have to enable developer mode (if I recall correctly). And that's described here: https://developers.ledger.com/docs/live-app/developer-mode/

**Comment by Modatech16** [comment]
I have the Nano X.
Thank you very much for answering my questions. This is all Greek to me but
I'm trying to get a buddy that knows a bit more to help me out.

**Comment by lthiery** [comment]
If I was not already familiar with the whole Ledger hardware thing, I would just follow the software approach: https://docs.solana.com/wallet-guide/paper-wallet#hierarchical-derivation

This exposes your seed to non-secure hardware, but I would just migrate all assets from that seed.

**Comment by k-thornton** [comment]
I wouldn't bother with side-loading development apps onto a Nano.  Too complicated even for a highly technical user.

If I understand correctly this issue could only occur if you used an Opolo-generated seed when setting up a Ledger, which is definitely not a good idea.  The seed you're using has already been exposed to non-secure hardware or else this problem wouldn't occur.  So in that sense, following the software approach seems like a reasonable alternative.

@Modatech16 Your solution here might be as simple as loading your Opolo-generated seed into the Helium Wallet app, and it might just work.  By doing this you'd be totally bypassing the Ledger and potentially compromising the seed.

Just, as @lthiery said, make sure if you're holding any value on any other blockchains, you'll want to move those funds away before putting your seed anywhere.

**Comment by Modatech16** [comment]
> I wouldn't bother with side-loading development apps onto a Nano. Too complicated even for a highly technical user.
> 
> If I understand correctly this issue could only occur if you used an Opolo-generated seed when setting up a Ledger, which is definitely not a good idea. The seed you're using has already been exposed to non-secure hardware or else this problem wouldn't occur. So in that sense, following the software approach seems like a reasonable alternative.
> 
> @Modatech16 Your solution here might be as simple as loading your Opolo-generated seed into the Helium Wallet app, and it might just work. By doing this you'd be totally bypassing the Ledger and potentially compromising the seed.
> 
> Just, as @lthiery said, make sure if you're holding any value on any other blockchains, you'll want to move those funds away before putting your seed anywhere.

Hello, and thank your information. 

I have the seed phrase loaded from the Opolo wallet in the Helium black app. I was hoping that would work when the black app first came out. Unfortunately, it doesn't work. 

I think that the private key that the HNT black app generates is derived differently because of the derivation path. Since I am not able to input the Opolo derivation path during the migration to the black app, I get a different private key generated that shows a different balance which is zero. 

Initially, through the first attempt of using the Helium-Solana-Ledger app I was able to get the HNT tokens that I had in account 0 of the Opolo wallet. But I had 4 other HNT addresses, with tokens, in the Opolo wallet that the migration wasn't able to read because of the derivation path. 

So I was able to get into Account 0 and transfer the HNT tokens using the Ledger Nano X but not account 1, 2, 3, 4. I had the different addresses for accounting purposes which I thought would have made things easier for me. It worked well for 18 months until Opolo rugged me and explained that this was a Helium issue. It took me 6 months of begging just to get the Opolo HNT derivation path from Opolo's CEO.

I have tried the paper wallet approach as recommended in this thread but I don't think that the Solana CLI is able to read the Opolo derivation path. 

I currently only have the HNT tokens that I cannot recover in the Opolo wallet. I created other SOL wallets on a Ledger wallet with Solflare for the few tokens that I was able to recover as well as the iOT and MOBILE tokens that I currently receive daily. The minute I can recover these HNT tokens from the Opolo wallet nightmare, I want to run over that wallet with my truck and forget this nightmare ever happened. 

I appreciate any and all advice. This issue keeps me up at night and there are a few others that I recommended this Opolo wallet to that are in the same boat. Feeling responsible for others that cannot access their HNT tokens because of me touting the Opolo as the only cold wallet that worked with HNT at the time, without CLI, is truly what makes me feel terrible. 

Thanks again for your time and input. It is greatly appreciated.
